#!/usr/bin/env bash

PACKAGE=hosts
SOURCE_DIR="${HOME}/work/src/dotfiles"
TARGET_DIR="${HOME}/work/src/hosts"

mkdir -p ${HOME}/src

if ! [ -d "${TARGET_DIR}" ]; then
	git clone https://github.com/StevenBlack/hosts.git "${TARGET_DIR}"
	pip3 install -r "${TARGET_DIR}/requirements.txt"
fi

stow "${PACKAGE}" -d "${SOURCE_DIR}" -t "${TARGET_DIR}"

pushd "${TARGET_DIR}" > /dev/null
python3 "updateHostsFile.py" --auto --replace --flush-dns-cache \
	--extensions social gambling porn
popd > /dev/null

